excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - identifier_name
  - multiple_closures_with_trailing_closure
  - unused_optional_binding

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
